SYMBOL_METADATA = {
    "005930": {
        "display_name": "삼성전자",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "반도체",
    },
    "000660": {
        "display_name": "SK하이닉스",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "반도체",
    },
    "035420": {
        "display_name": "NAVER",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "플랫폼",
    },
    "035720": {
        "display_name": "카카오",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "플랫폼",
    },
    "005380": {
        "display_name": "현대차",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "자동차",
    },
    "000270": {
        "display_name": "기아",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "자동차",
    },
    "051910": {
        "display_name": "LG화학",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "화학/배터리",
    },
    "068270": {
        "display_name": "셀트리온",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "바이오",
    },
    "373220": {
        "display_name": "LG에너지솔루션",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "배터리",
    },
    "006400": {
        "display_name": "삼성SDI",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "배터리",
    },
    "009150": {
        "display_name": "삼성전기",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "전자부품",
    },
    "207940": {
        "display_name": "삼성바이오로직스",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "바이오",
    },
    "105560": {
        "display_name": "KB금융",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "금융",
    },
    "055550": {
        "display_name": "신한지주",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "금융",
    },
    "086790": {
        "display_name": "하나금융지주",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "금융",
    },
    "012330": {
        "display_name": "현대모비스",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "자동차 부품",
    },
    "028260": {
        "display_name": "삼성물산",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "지주/산업재",
    },
    "066570": {
        "display_name": "LG전자",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "가전/전장",
    },
    "096770": {
        "display_name": "SK이노베이션",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "에너지/배터리",
    },
    "003550": {
        "display_name": "LG",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "지주",
    },
    "034020": {
        "display_name": "두산에너빌리티",
        "asset_type": "STOCK",
        "market": "KR",
        "sector": "산업재",
    },
    "AAPL": {
        "display_name": "Apple",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "빅테크",
    },
    "MSFT": {
        "display_name": "Microsoft",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "빅테크",
    },
    "NVDA": {
        "display_name": "NVIDIA",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "AI 반도체",
    },
    "TSLA": {
        "display_name": "Tesla",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "전기차",
    },
    "AMZN": {
        "display_name": "Amazon",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "빅테크/소비",
    },
    "GOOGL": {
        "display_name": "Alphabet",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "빅테크",
    },
    "META": {
        "display_name": "Meta",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "빅테크",
    },
    "AMD": {
        "display_name": "AMD",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "반도체",
    },
    "AVGO": {
        "display_name": "Broadcom",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "반도체",
    },
    "LLY": {
        "display_name": "Eli Lilly",
        "asset_type": "STOCK",
        "market": "US",
        "sector": "헬스케어",
    },
    "BTCUSDT": {
        "display_name": "Bitcoin",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "가상자산 대장주",
    },
    "ETHUSDT": {
        "display_name": "Ethereum",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "스마트컨트랙트",
    },
    "SOLUSDT": {
        "display_name": "Solana",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "레이어1",
    },
    "XRPUSDT": {
        "display_name": "XRP",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "송금/결제",
    },
    "BNBUSDT": {
        "display_name": "BNB",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "거래소 토큰",
    },
    "DOGEUSDT": {
        "display_name": "Dogecoin",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "밈코인",
    },
    "ADAUSDT": {
        "display_name": "Cardano",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "레이어1",
    },
    "AVAXUSDT": {
        "display_name": "Avalanche",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "레이어1",
    },
    "LINKUSDT": {
        "display_name": "Chainlink",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "오라클",
    },
    "DOTUSDT": {
        "display_name": "Polkadot",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "인터체인",
    },
    "TRXUSDT": {
        "display_name": "TRON",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "레이어1",
    },
    "LTCUSDT": {
        "display_name": "Litecoin",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "결제",
    },
    "BCHUSDT": {
        "display_name": "Bitcoin Cash",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "결제",
    },
    "NEARUSDT": {
        "display_name": "NEAR Protocol",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "레이어1",
    },
    "APTUSDT": {
        "display_name": "Aptos",
        "asset_type": "CRYPTO",
        "market": "USDT",
        "sector": "레이어1",
    },
}


def enrich_symbol(row: dict) -> dict:
    symbol = str(row.get("symbol", "")).upper()
    metadata = SYMBOL_METADATA.get(symbol, {})
    return {
        **row,
        "display_name": metadata.get("display_name", symbol),
        "market": metadata.get("market") or row.get("market_country") or row.get("currency") or "",
        "sector": metadata.get("sector", ""),
    }
