-- 1. 사용자 프로필 테이블 (Supabase auth.users 연동 및 nickname, phone 컬럼 포함)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    nickname TEXT,
    phone TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "사용자는 자신의 프로필만 조회 및 수정 가능" ON public.profiles
    FOR ALL USING (auth.uid() = id);

-- auth.users 트리거 설정 (nickname, phone 동기화 반영)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, nickname, phone)
    VALUES (
        new.id, 
        new.email, 
        COALESCE(new.raw_user_meta_data->>'nickname', ''),
        COALESCE(new.raw_user_meta_data->>'phone', '')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 2. 거래소/증권사 API Key 및 계좌 설정 테이블
CREATE TABLE public.user_api_keys (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    exchange TEXT NOT NULL CHECK (exchange IN ('UPBIT', 'KIS')),
    encrypted_access_key TEXT NOT NULL, 
    encrypted_secret_key TEXT NOT NULL, 
    kis_account_no TEXT,               
    kis_account_code TEXT DEFAULT '01',
    kis_env TEXT DEFAULT 'MOCK' CHECK (kis_env IN ('MOCK', 'REAL')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, exchange, kis_env)
);

ALTER TABLE public.user_api_keys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "사용자는 자신의 API Key 레코드만 관리 가능" ON public.user_api_keys
    FOR ALL USING (auth.uid() = user_id);


-- 3. 가상자산 페이퍼 트레이딩 (업비트 모의투자용) 및 가상 자산 대시보드 테이블
CREATE TABLE public.paper_portfolios (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    asset_type TEXT NOT NULL CHECK (asset_type IN ('CRYPTO', 'STOCK')),
    ticker TEXT NOT NULL,
    average_buy_price NUMERIC DEFAULT 0 NOT NULL,
    volume NUMERIC DEFAULT 0 NOT NULL,
    virtual_cash NUMERIC DEFAULT 10000000 NOT NULL, -- 기본 1,000만 원 모의 원화 제공
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, asset_type, ticker)
);

ALTER TABLE public.paper_portfolios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "사용자는 자신의 가상 잔고만 관리 가능" ON public.paper_portfolios
    FOR ALL USING (auth.uid() = user_id);


-- 4. 챗봇 대화 이력 테이블
CREATE TABLE public.chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "사용자는 자신의 대화 이력만 조회 및 저장 가능" ON public.chat_history
    FOR ALL USING (auth.uid() = user_id);


-- 5. 주식 / 가상자산 매매 승인 제안 테이블 (Human-in-the-Loop)
CREATE TABLE public.trade_proposals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    exchange TEXT NOT NULL CHECK (exchange IN ('UPBIT', 'KIS')),
    asset_type TEXT NOT NULL CHECK (asset_type IN ('CRYPTO', 'STOCK')),
    ticker TEXT NOT NULL, 
    side TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
    price NUMERIC, 
    volume NUMERIC NOT NULL, 
    ord_type TEXT NOT NULL CHECK (ord_type IN ('LIMIT', 'MARKET')),
    status TEXT DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXECUTED', 'FAILED')),
    failure_reason TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- realtime publication에 테이블 등록
ALTER publication supabase_realtime ADD TABLE public.trade_proposals;

ALTER TABLE public.trade_proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "사용자는 자신의 매매 제안 내역만 조회 및 관리 가능" ON public.trade_proposals
    FOR ALL USING (auth.uid() = user_id);


-- 6. 주식 / 가상자산 조건식 자동 트레이딩 규칙 테이블
CREATE TABLE public.auto_trading_rules (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    exchange TEXT NOT NULL CHECK (exchange IN ('UPBIT', 'KIS')),
    asset_type TEXT NOT NULL CHECK (asset_type IN ('CRYPTO', 'STOCK')),
    ticker TEXT NOT NULL, 
    entry_price NUMERIC NOT NULL, 
    investment_amount NUMERIC NOT NULL, 
    target_profit_rate NUMERIC NOT NULL,
    stop_loss_rate NUMERIC NOT NULL,
    status TEXT DEFAULT 'RUNNING' NOT NULL CHECK (status IN ('RUNNING', 'COMPLETED', 'STOPPED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.auto_trading_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "사용자는 자신의 자동 트레이딩 규칙만 관리 가능" ON public.auto_trading_rules
    FOR ALL USING (auth.uid() = user_id);
